# Action to send a notification to Google Chat on "push".

name: Send Google Chat notification

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GCWEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "text": "🚀 ${{ github.event.head_commit.message }}\n\nCommit URL: <${{ github.event.head_commit.url }}>\nDeployment triggered by: *${{ github.event.head_commit.author.name }}*"
          }'